DancingGoat/Controllers/PartnershipController.cs
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class PartnershipController : AsyncController
    {
        public ActionResult Index()
        {
            ViewBag.PartnershipRequested = TempData["formApplied"] ?? false;
            return View();
        }
        
        /// <summary>
        /// Dummy action; form information is being handed over to Kentico Cloud Engagement management service through JavaScript.
        /// </summary>
        [HttpPost]
        public ActionResult Application()
        {
            // If needed, put your code here to work with the uploaded data in MVC.
            TempData["formApplied"] = true;
            return RedirectToAction("Index");
        }
    }
}

DancingGoat/Views/Partnership/Index.cshtml
@model dynamic

@{
    ViewBag.Title = Resources.DancingGoat.Partnership;
}

<div class="row">
    <div class="col-md-6">
        <div class="partnership-info partnership-info-left">

            <h3>@Resources.DancingGoat.Partnership_LeftInfoTitle</h3>

            <ul>
                <li>@Resources.DancingGoat.Partnership_LeftInfoItem1</li>
                <li>@Resources.DancingGoat.Partnership_LeftInfoItem2</li>
                <li>@Resources.DancingGoat.Partnership_LeftInfoItem3</li>
            </ul>

        </div>
    </div>
    <div class="col-md-6">
        <div class="partnership-info partnership-info-right">

            <h3>@Resources.DancingGoat.Partnership_RightInfoTitle</h3>

            <ul>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem1</li>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem2</li>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem3</li>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem4</li>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem5</li>
                <li>@Resources.DancingGoat.Partnership_RightInfoItem6</li>
            </ul>

        </div>
    </div>
</div>



<section class="row text-and-image">
    <h3 class="col-lg-12">
        @Resources.DancingGoat.Partnership_Title
    </h3>
    <div>
       @Html.Raw(Resources.DancingGoat.Partnership_Text)
    </div>
</section>

<section class="row" id="lp-form">
    <div class="container">
        <h3> @Resources.DancingGoat.Partnership_ApplicationTitle</h3>
        <div class="row">
            <div class="col-md-5">
                <div> @Resources.DancingGoat.Partnership_ApplicationText </div>
            </div>

            <div class="col-md-6 col-md-offset-1">
                @if (ViewBag.PartnershipRequested)
                {
                    <div class="partnership-info-right">
                        <span class="InfoLabel">@Resources.DancingGoat.Partnership_RequestLabel</span>
                    </div>
                }
                else
                {
                    <div id="pnlForm" class="FormPanel">
                        @using (Html.BeginForm("Application", "Partnership", FormMethod.Post, new { id = "partnership-application" }))
                        {
                            <div class="form-group">
                                <div class="form-group-label">
                                    <strong><label id="CompanyName_lb" for="CompanyName_txtText">@Resources.DancingGoat.Partnership_Form_CompanyName</label></strong>
                                </div>
                                <div class="form-group-input">
                                    <input name="CompanyName" type="text" maxlength="200" id="CompanyName_txtText" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-group-label">
                                    <strong><label id="FirstName_lb" for="FirstName_txtText">@Resources.DancingGoat.Partnership_Form_FirstName</label></strong>
                                </div>
                                <div class="form-group-input">
                                    <input name="FirstName" type="text" maxlength="200" id="FirstName_txtText" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-group-label">
                                    <strong><label id="LastName_lb" for="LastName_txtText">@Resources.DancingGoat.Partnership_Form_LastName</label></strong>
                                </div>
                                <div class="form-group-input">
                                    <input name="LastName" type="text" maxlength="200" id="LastName_txtText" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-group-label">
                                    <strong><label id="Phone_lb" for="Phone_txtText">@Resources.DancingGoat.Partnership_Form_Phone</label></strong> (optional)
                                </div>
                                <div class="form-group-input">
                                    <input name="Phone" type="text" maxlength="200" id="Phone_txtText" class="form-control" />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-group-label">
                                    <strong><label id="Email_lb" for="Email_txtEmailInput">@Resources.DancingGoat.Partnership_Form_Email</label></strong>
                                </div>
                                <div class="form-group-input">
                                    <input name="Email" type="text" maxlength="254" id="Email_txtEmailInput" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <fieldset class="partnership-form-fieldset">
                                    <legend class="form-group-label"><strong>@Resources.DancingGoat.Partnership_Form_Interest</strong></legend>
                                    <span id="BecomePartner_list" class="radio radio-list-vertical">
                                        <input id="BecomePartner_list_0" type="radio" name="BecomePartner" value="wholesale partner"/>
                                        <label for="BecomePartner_list_0">@Resources.DancingGoat.Partnership_Form_Interest_WholesalePartner</label>
                                    </span>
                                    <span id="BecomePartner_list" class="radio radio-list-vertical">
                                        <input id="BecomePartner_list_1" type="radio" name="BecomePartner" value="partner café"/>
                                        <label for="BecomePartner_list_1">@Resources.DancingGoat.Partnership_Form_Interest_PartnerCafe</label>
                                    </span>
                                </fieldset>
                            </div>

                            <div class="form-group">
                                <input type="submit" name="btnOK" value="@Resources.DancingGoat.Partnership_Form_Apply" class="btn btn-primary" />
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $("#partnership-application").validate({
                errorClass: "message message-error",
                rules: {
                    Email: "email",
                    Phone: "digits"
                }
            });
        });
    </script>
}