DancingGoat/Controllers/AboutController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

using DancingGoat.Models;

using KenticoCloud.ContentManagement.Helpers.Models;
using KenticoCloud.Delivery;

namespace DancingGoat.Controllers
{
    public class AboutController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var response = await client.GetItemAsync<AboutUs>("about_us");

            var viewModel = new AboutUsViewModel
            {
                ItemId = response.Item.System.Id,
                Language = response.Item.System.Language,
                FactViewModels = MapFactsAboutUs(response)
            };

            return View(viewModel);
        }

        private IList<FactAboutUsViewModel> MapFactsAboutUs(DeliveryItemResponse<AboutUs> response)
        {
            var facts = new List<FactAboutUsViewModel>();

            if (response.Item == null)
            {
                return facts;
            }

            int i = 0;

            foreach (var fact in response.Item.Facts)
            {
                var factViewModel = new FactAboutUsViewModel
                {
                    Fact = (FactAboutUs)fact,
                    ParentItemElementIdentifier = new ElementIdentifier(response.Item.System.Id, AboutUs.FactsCodename)
                };

                if (i++ % 2 == 0)
                {
                    factViewModel.Odd = true;
                }

                facts.Add(factViewModel);
            }

            return facts;
        }
    }
}

DancingGoat/Controllers/BrewersController.cs
using DancingGoat.Models;
using KenticoCloud.Delivery;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class BrewersController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var itemsTask = client.GetItemsAsync<Brewer>(
                new EqualsFilter("system.type", "brewer"),
                new OrderParameter("elements.product_name"),
                new ElementsParameter(Brewer.ImageCodename, Brewer.PriceCodename, Brewer.ProductStatusCodename, Brewer.ProductNameCodename, Brewer.UrlPatternCodename),
                new DepthParameter(0)
            );

            var statusTask = client.GetTaxonomyAsync(Brewer.ProductStatusCodename);
            var manufacturerTask = client.GetTaxonomyAsync(Brewer.ManufacturerCodename);

            var model = new BrewersViewModel
            {
                Items = (await itemsTask).Items,
                Filter = new BrewerFilterViewModel
                {
                    AvailableProductStatuses = GetTaxonomiesAsSelectList(await statusTask),
                    AvailableManufacturers = GetTaxonomiesAsSelectList(await manufacturerTask)
                }
            };

            return View(model);
        }

        public async Task<ActionResult> Filter(BrewerFilterViewModel model)
        {
            var parameters = new List<IQueryParameter> {
                new EqualsFilter("system.type", "brewer"),
                new OrderParameter("elements.product_name"),
                new ElementsParameter(Brewer.ImageCodename, Brewer.PriceCodename, Brewer.ProductStatusCodename, Brewer.ProductNameCodename, Brewer.UrlPatternCodename),
                new DepthParameter(0)
            };

            var manufacturers = model.GetFilteredManufacturers().ToArray();
            if (manufacturers.Any())
            {
                parameters.Add(new AnyFilter($"elements.{Brewer.ManufacturerCodename}", manufacturers));
            }

            var statusTypes = model.GetFilteredProductStatuses().ToArray();
            if (statusTypes.Any())
            {
                parameters.Add(new AnyFilter($"elements.{Brewer.ProductStatusCodename}", statusTypes));
            }

            var response = await client.GetItemsAsync<Brewer>(parameters);

            return PartialView("ProductListing", response.Items);
        }

        private IList<SelectListItem> GetTaxonomiesAsSelectList(TaxonomyGroup taxonomyGroup)
        {
            return taxonomyGroup.Terms.Select(x => new SelectListItem{Text = x.Name, Value = x.Codename}).ToList();
        }
    }
}

DancingGoat/Controllers/CafesController.cs
using DancingGoat.Models;
using KenticoCloud.Delivery;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class CafesController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var response = await client.GetItemsAsync<Cafe>(
                new EqualsFilter("system.type", "cafe"),
                new OrderParameter("system.name")
            );
            var cafes = response.Items;

            var viewModel = new CafesViewModel
            {
                CompanyCafes = cafes.Where(c => c.Country == "USA").ToList(),
                PartnerCafes = cafes.Where(c => c.Country != "USA").ToList()
            };

            return View(viewModel);
        }
    }
}

DancingGoat/Controllers/CoffeesController.cs
using DancingGoat.Models;
using KenticoCloud.Delivery;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class CoffeesController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var itemsTask = client.GetItemsAsync<Coffee>(
                new EqualsFilter("system.type", "coffee"),
                new OrderParameter("elements.product_name"),
                new ElementsParameter(Coffee.ImageCodename, Coffee.PriceCodename, Coffee.ProductStatusCodename, Coffee.ProductNameCodename, Coffee.UrlPatternCodename),
                new DepthParameter(0)
            );

            var processingTask = client.GetTaxonomyAsync(Coffee.ProcessingCodename);
            var statusTask = client.GetTaxonomyAsync(Coffee.ProductStatusCodename);

            var model = new CoffeesViewModel
            {
                Items = (await itemsTask).Items,
                Filter = new CoffeesFilterViewModel
                {
                    AvailableProcessings = GetTaxonomiesAsSelectList(await processingTask),
                    AvailableProductStatuses = GetTaxonomiesAsSelectList(await statusTask)
                }
            };

            return View(model);
        }

        public async Task<ActionResult> Filter(CoffeesFilterViewModel model)
        {
            var parameters = new List<IQueryParameter> {
                new EqualsFilter("system.type", "coffee"),
                new OrderParameter("elements.product_name"),
                new ElementsParameter(Coffee.ImageCodename, Coffee.PriceCodename, Coffee.ProductStatusCodename, Coffee.ProductNameCodename, Coffee.UrlPatternCodename),
                new DepthParameter(0),
            };

            var filterProcessing = model.GetFilteredProcessings().ToArray();
            if (filterProcessing.Any())
            {
                parameters.Add(new AnyFilter($"elements.{Coffee.ProcessingCodename}", filterProcessing));
            }

            var filterStatus = model.GetFilteredProductStatuses().ToArray();
            if (filterStatus.Any())
            {
                parameters.Add(new AnyFilter($"elements.{Coffee.ProductStatusCodename}", filterStatus));
            }

            var response = await client.GetItemsAsync<Coffee>(parameters);

            return PartialView("ProductListing", response.Items);
        }

        private IList<SelectListItem> GetTaxonomiesAsSelectList(TaxonomyGroup taxonomyGroup)
        {
            return taxonomyGroup.Terms.Select(x => new SelectListItem { Text = x.Name, Value = x.Codename }).ToList();
        }
    }
}

DancingGoat/Views/Shared/EditModePanel.cshtml
@model DancingGoat.Models.EditPanelViewModel

<div class="edit-mode-panel">
    <div>
        <div class="edit-mode-panel__toggle">
            <label class="switch">
                <input id="edit-mode-switch" type="checkbox" onchange="toggleEditMode(this.checked)" autocomplete="off">
                <span class="slider round"></span>
            </label>
        </div>
        <div class="edit-mode-panel__caption">
            <span class="edit-mode-panel__title">Edit mode</span>
        </div>
    </div>
    <div class="edit-mode-panel__navigate-link">
        <a target="_blank" href="@Model.ItemUrl">Open content item in KC</a>
    </div>
</div>

DancingGoat/Views/Shared/HeadersMetadata.cshtml
@model DancingGoat.Models.IMetadata

<meta name=”description” content="@Model.MetadataMetaDescription" />

<meta property="og:title" content="@Model.MetadataOgTitle" />
<meta property="og:type" content="website" />
<meta property="og:url" content="@(Request.Url?.AbsoluteUri)" />
<meta property="og:image" content="@(Model.MetadataOgImage.FirstOrDefault()?.Url)" />
<meta property="og:description" content="@Model.MetadataOgDescription" />

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@Model.MetadataTwitterSite">
<meta name="twitter:creator" content="@Model.MetadataTwitterCreator">
<meta name="twitter:title" content="@Model.MetadataTwitterTitle">
<meta name="twitter:description" content="@Model.MetadataOgDescription">
<meta name="twitter:image" content="@(Model.MetadataTwitterImage.FirstOrDefault()?.Url)">

DancingGoat/Views/Shared/ProductListing.cshtml
@model IEnumerable<DancingGoat.Models.IProduct>

@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 3 products on row for large screen -->
        <div class="col-md-6 col-lg-4">
            @Html.DisplayFor(m => product, "Product")
        </div>
    }
}
else
{
    <span class="ContentLabel">@Resources.DancingGoat.Brewers_NoMatchingProducts</span>
}

DancingGoat/Views/Shared/_Layout.cshtml
@using System.Configuration
@using DancingGoat.Controllers
@using DancingGoat.Helpers
@using DancingGoat.Models
<!DOCTYPE html>

<html>
<head id="head">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
    <title>@ViewBag.Title - Dancing Goat</title>
    <link href="@Url.Content("~/Content/Styles/Site.css")" rel="stylesheet" type="text/css" />
    @RenderSection("headers", required: false)
</head>
<body>
    <div class="page-wrap">
        <header class="header" role="banner">
            <div class="menu">
                <div class="container">
                    <nav role="navigation">
                        <ul>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Home, "Index", "Home")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Store, "Index", "Coffees")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Articles, "Index", "Articles")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.AboutUs, "Index", "About")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Cafes, "Index", "Cafes")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Contact, "Index", "Contacts")
                            </li>
                            <li>
                                @Html.ActionLink(Resources.DancingGoat.Partnership, "Index", "Partnership")
                            </li>
                        </ul>
                    </nav>
                    <div class="additional-menu-buttons user-menu">
                        <nav role="navigation">
                            <ul class="dropdown-items-list dropdown-desktop-visible">
                                <li>
                                    @Html.ActionLink("English", "Index", "LanguageSelector", LanguageSwitchHelper.GetLangugageSwitchParameters(ViewContext.RouteData.Values, "en-us", Model as IDetailItem), null)
                                </li>
                                <li>
                                    @Html.ActionLink("Español", "Index", "LanguageSelector", LanguageSwitchHelper.GetLangugageSwitchParameters(ViewContext.RouteData.Values, "es-es", Model as IDetailItem), null)
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div id="message-box" class="container message">
                @Html.Partial("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml")
            </div>
            <div class="header-row">
                <div class="container">
                    <div class="col-xs-8 col-md-8 col-lg-4 logo">
                        <h1 class="logo">
                            @Html.ActionLink("Dancing Goat", "Index", new { controller = "Home" }, new { @class = "logo-link" })
                        </h1>
                    </div>
                </div>
            </div>
        </header>
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div class="footer-wrapper">
        <footer role="contentinfo">
            <div class="footer-container">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 footer-col">
                            <p>
                                @Html.Action("CompanyAddress", "Home")
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-4 footer-col">
                            <h3>@Resources.DancingGoat.FollowUs_Title</h3>
                            <a class="followus-link" href="https://www.facebook.com/Dancing.Goat" target="_blank">
                                <img alt="@Resources.DancingGoat.FollowUsOnFacebook" class="" src="~/Content/Images/facebook-icon.png" title="@Resources.DancingGoat.FollowUsOnFacebook">
                            </a>
                            <a class="followus-link" href="https://twitter.com/DancingGoat78" target="_blank">
                                <img alt="@Resources.DancingGoat.FollowUsOnTwitter" class="" src="~/Content/Images/twitter-icon.png" title="@Resources.DancingGoat.FollowUsOnTwitter">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container copyright">
                Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        !function(){var a='https://engage-ket.kenticocloud.com/js',b=document,c=b.createElement('script'),d=b.getElementsByTagName('script')[0];c.type='text/javascript',c.async=!0,c.defer=!0,c.src=a+'?d='+document.domain,d.parentNode.insertBefore(c,d)}(),window.ket=window.ket||function(){(ket.q=ket.q||[]).push(arguments)};
        ket('start', '@ConfigurationManager.AppSettings["ProjectId"]');
    </script>
    <script type="text/javascript">
        function toggleEditMode(isChecked) {
            const body = document.getElementsByTagName('body')[0];
            isChecked ? body.classList.add('edit-mode') : body.classList.remove('edit-mode');
        }
    </script>


</body>
</html>

DancingGoat/Views/Shared/_ProductLayout.cshtml
@using KenticoCloud.Delivery
@model DancingGoat.Models.IProduct
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.ProductProductName;
}
@section headers
{
    @Html.Partial("HeadersMetadata", Model)
}

<article class="product-detail">
    <div class="row">
        <div class="col-md-12">
            <header>
                <h2>@Html.DisplayFor(vm => vm.ProductProductName)</h2>
            </header>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-lg-7 col-md-6">
            <figure class="image">
                @Html.AssetImage(Model.ProductImage.FirstOrDefault())
            </figure>
            <div class="description">
                @Html.Raw(string.Join("\n", Model.ProductShortDescription?.Blocks ?? (Model.ProductLongDescription?.Blocks ?? Enumerable.Empty<IRichTextBlock>())))
                @RenderSection("ProductSpecificProperties", false)
            </div>
        </div>
        @RenderSection("ProductSpecificForm", false)
    </div>
</article>

@section Scripts
{
    @RenderSection("Scripts", false)
}

DancingGoat/Views/Shared/_StoreLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container product-page-container">
    <nav role="navigation" class="sub-menu row">
        <div class="store-menu-list row">
            <ul>
                <li>
                    @Html.ActionLink(Resources.DancingGoat.Coffees, "Index", "Coffees")
                </li>
                <li>
                    @Html.ActionLink(Resources.DancingGoat.Brewers, "Index", "Brewers")
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
</div>

@section Scripts {
    @RenderSection("scripts", required: false)
}